export const baseURL = "http://localhost:3000/"
export const apiVersion = "v1"
export const loginEndpoint = "/user/login"
export const registerEndpoint = "/user/signup"
export const logoutEndpoint = "/user/logout"
export const tokenType = "JWT"