export const baseURL = "http://localhost:3000/"
export const apiVersion = "v1"
export const loginEndpoint = "/user/signin"
export const registerEndpoint = "/user/signup"
export const logoutEndpoint = "/user/signout"
export const tokenType = "JWT"